// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HomePage: typeof import('./components/HomePage.vue')['default']
    Runkit: typeof import('./components/Runkit.vue')['default']
  }
}

export {}
