<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>styl</string>
		<string>stylus</string>
	</array>
	<key>name</key>
	<string>Stylus</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^ *(&amp;|)</string>
			<key>name</key>
			<string>variable.language.stylus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(arguments)</string>
			<key>name</key>
			<string>variable.language.stylus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@([-\w]+)</string>
			<key>name</key>
			<string>keyword.stylus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.stylus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\.)[a-zA-Z0-9_-]+</string>
			<key>name</key>
			<string>entity.other.attribute-name.class.stylus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.stylus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(:+)\b(after|before|first-child|first-letter|first-line|selection)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.pseudo-element.stylus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.stylus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(:)\b(active|hover|link|visited|focus)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.pseudo-class.stylus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.css</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)[a-zA-Z][a-zA-Z0-9_-]*</string>
			<key>name</key>
			<string>entity.other.attribute-name.id.stylus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(!important|for|in|return|true|false|null|if|else|unless|return)\b</string>
			<key>name</key>
			<string>keyword.control.stylus</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.stylus</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.stylus</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\b(\d+))|(#[a-fA-F0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.stylus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.stylus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^[ \t]+)?(\/\/).*$\n?</string>
			<key>name</key>
			<string>comment.line.stylus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.stylus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([-a-zA-Z_][-\w]*)?(\()</string>
			<key>name</key>
			<string>meta.function.stylus</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.stylus</string>
	<key>uuid</key>
	<string>60519324-6A3A-4382-9E0B-546993A3869A</string>
</dict>
</plist>
